version: '3'
services:

  app:
    build:
      context: ./
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - .:/var/www/

  cache:
    image: redis
    restart: always

  web:
    build:
      context: ./
      dockerfile: web.dockerfile
    working_dir: /var/www
    ports:
      - 80:80
    depends_on:
      - app
    volumes:
      - ./:/var/www/

volumes:
  dbdata:
