# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.2-node-browsers
      - image: circleci/node:chakracore-browsers-legacy

    steps:
      - checkout
      - restore_cache:
          key: v1-php
      - save_cache:
          key: v1-php
          paths: 
            - phpcs.phar
      - run: php phpcs.phar --config-set default_standard PSR2
      - run: php phpcs.phar -n --exclude=PSR1.Classes.ClassDeclaration --extensions=php app database resources routes tests
      - restore_cache:
          key: v2-npm
      - run: sudo npm install
      - run: sudo npm i -g eslint
      - save_cache:
          key: v2-npm
          paths: 
            - /node_modules
      - run: eslint --no-eslintrc --env es6 resources
